#!/usr/bin/env bash
set -Eeuo pipefail
HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CORE="$HERE/rsync-backup-tui-object-core.sh"
[[ -r $CORE ]] || { echo "Missing object-aware core: $CORE" >&2; exit 1; }
source <(sed '$d' "$CORE")
VER='2.3'
eval "$(declare -f summary | sed '1s/^summary /summary_v22 /')"
eval "$(declare -f execute | sed '1s/^execute /execute_v22 /')"
TRANSPORT=local; NET_SCOPE=LAN
SSH_HOST=''; SSH_USER="${USER:-}"; SSH_PORT=22; SSH_KEY=''; SSH_COMP=0
REMOTE_PATH='~/backups/'; REMOTE_IS_DIR=1
private_host(){ local h=${1,,};[[ $h == localhost || $h == *.local || $h == 127.* || $h == 10.* || $h == 192.168.* ]]&&return 0;[[ $h =~ ^172\.([1][6-9]|2[0-9]|3[01])\. ]]&&return 0;[[ $h == ::1 || $h == fc*:* || $h == fd*:* || $h == fe80:* ]]&&return 0;return 1; }
transport_choose(){ local -a opts keys;local c;opts=('Local mounted storage — current behavior');keys=(local);if have ssh&&have rsync&&[[ $SRC_KIND != block ]];then opts+=('Direct rsync over SSH — recommended for LAN/WAN incremental copy');keys+=(rsync-ssh);fi;if have ssh&&have scp;then opts+=('Local backup first, then SCP result — useful for archives/images');keys+=(scp-after);fi;c=$(choose 'Destination transport' 0 "${opts[@]}");TRANSPORT=${keys[c]};log "TRANSPORT selected=$TRANSPORT"; }
ssh_target(){ local h=$SSH_HOST;[[ $h == *:* && $h != \[*\] ]]&&h="[$h]";printf '%s@%s' "$SSH_USER" "$h"; }
ssh_base(){ local -n out=$1;out=(ssh -p "$SSH_PORT");[[ -n $SSH_KEY ]]&&out+=(-i "$SSH_KEY");((SSH_COMP))&&out+=(-C);out+=("$(ssh_target)"); }
scp_base(){ local -n out=$1;out=(scp -P "$SSH_PORT");[[ -n $SSH_KEY ]]&&out+=(-i "$SSH_KEY");((SSH_COMP))&&out+=(-C); }
network_config(){ local d c test_rc=0;local -a a sshc;ui;echo 'SSH authentication is handled by OpenSSH.';echo 'Passwords/passphrases are requested interactively by ssh/scp and are never stored or logged.';echo 'Existing ssh-agent and ~/.ssh/config settings remain usable.';echo;SSH_HOST=$(ask 'Remote host / IP' "$SSH_HOST");[[ -n $SSH_HOST ]]||{ echo 'Remote host is required.' >&2;return 2; };SSH_USER=$(ask 'Remote SSH user' "${SSH_USER:-$USER}");SSH_PORT=$(ask 'SSH port' '22');SSH_KEY=$(ask 'Identity file (blank = ssh-agent/config/password)' '');[[ -z $SSH_KEY || -r $SSH_KEY ]]||{ ui;echo "Identity file is not readable: $SSH_KEY";waitkey;SSH_KEY=''; };if private_host "$SSH_HOST";then d=0;else d=1;fi;a=('LAN / trusted local network' 'WAN / Internet / VPN');c=$(choose 'Network scope (used for recommendations only)' "$d" "${a[@]}");((c==0))&&NET_SCOPE=LAN||NET_SCOPE=WAN;REMOTE_PATH=$(ask 'Remote destination path' '~/backups/');REMOTE_IS_DIR=0;yes 'Treat remote path as a directory?' Y&&REMOTE_IS_DIR=1||:;SSH_COMP=0;d=N;if [[ $NET_SCOPE == WAN && $TRANSPORT == rsync-ssh ]]&&! compressed_file;then d=Y;fi;ui;echo 'SSH transport compression (-C) can help text-heavy data over slow WAN links.';echo 'It often wastes CPU for zstd/ZIP/media/already-compressed data and usually brings little benefit on LAN.';echo;yes 'Enable SSH transport compression (-C)?' "$d"&&SSH_COMP=1||:;log "NETWORK scope=$NET_SCOPE transport=$TRANSPORT host=$SSH_HOST user=$SSH_USER port=$SSH_PORT key=$([[ -n $SSH_KEY ]]&&echo custom||echo default) ssh_compress=$SSH_COMP remote_path=$REMOTE_PATH remote_is_dir=$REMOTE_IS_DIR";if yes 'Test SSH connection now? (OpenSSH may ask for password/key passphrase)' Y;then ssh_base sshc;ui;echo "Testing SSH connection to $(ssh_target):$SSH_PORT ...";echo;if "${sshc[@]}" -- true;then echo 'SSH connection: OK';log 'SSH_TEST rc=0';else test_rc=$?;echo "SSH connection failed (rc=$test_rc).";log "SSH_TEST rc=$test_rc";yes 'Continue anyway?' N||return "$test_rc";fi;waitkey;fi;if ((REMOTE_IS_DIR))&&yes 'Create remote destination directory if missing?' Y;then ssh_base sshc;"${sshc[@]}" -- mkdir -p -- "$REMOTE_PATH";log 'REMOTE_MKDIR requested=1';fi; }
remote_fs_probe(){ local -a s;local fs;ssh_base s;fs=$("${s[@]}" -- findmnt -T "$REMOTE_PATH" -rn -o FSTYPE 2>/dev/null|head -1||:);[[ -n $fs ]]&&DFS=$fs||DFS=remote;DDEV="ssh:$(ssh_target)";DMEDIA="NETWORK-$NET_SCOPE";DLINK=0; }
remote_rsync_execute(){ local flags='-aS' x sshcmd dest;local -a args=() sshv;((RSYNC_ACL))&&flags+='A';((RSYNC_XATTR))&&flags+='X';((RSYNC_HARD))&&flags+='H';sshv=(ssh -p "$SSH_PORT");[[ -n $SSH_KEY ]]&&sshv+=(-i "$SSH_KEY");((SSH_COMP))&&sshv+=(-C);sshcmd=$(q "${sshv[@]}");dest="$(ssh_target):$REMOTE_PATH";args=(rsync "$flags" --info=progress2 --stats -e "$sshcmd");((RSYNC_NUMID))&&args+=(--numeric-ids);((RSYNC_DELETE))&&args+=(--delete);if [[ $SRC_KIND == directory || $SRC_KIND == mountpoint ]];then for x in "${EX[@]}";do args+=(--exclude "$x");done;((SSH_COMP))&&args+=(--compress);args+=("${SRC%/}/" "$dest");else ((SSH_COMP))&&args+=(--compress);args+=("$SRC" "$dest");fi;runlog rsync-ssh "${args[@]}"; }
scp_after_execute(){ local rc target;local -a a;execute_v22||return $?;scp_base a;[[ -d $OUT ]]&&a+=(-r);target="$(ssh_target):$REMOTE_PATH";ui;echo "Local backup completed. Sending result via SCP to $target";echo 'OpenSSH may ask for a password/key passphrase; it is never logged.';echo;a+=("$OUT" "$target");if runlog scp-after "${a[@]}";then rc=0;else rc=$?;fi;return "$rc"; }
summary(){ summary_v22;echo "Transport: $TRANSPORT";if [[ $TRANSPORT != local ]];then echo "Network scope: $NET_SCOPE";echo "SSH target: $(ssh_target):$SSH_PORT";echo "Remote path: $REMOTE_PATH ($([[ $REMOTE_IS_DIR == 1 ]]&&echo directory||echo exact-path))";echo "SSH compression: $([[ $SSH_COMP == 1 ]]&&echo yes||echo no)";echo "SSH identity: $([[ -n $SSH_KEY ]]&&echo custom-key||echo agent/config/password)";[[ $TRANSPORT == rsync-ssh ]]&&echo 'Local output path: not used — transfer is direct';[[ $TRANSPORT == scp-after ]]&&echo 'Transfer order: create local backup first, then SCP the result';fi;echo; }
execute(){ case $TRANSPORT in local)execute_v22;;rsync-ssh)remote_rsync_execute;;scp-after)scp_after_execute;;esac; }
main(){ [[ ${1:-} == --self-test ]]&&{ self;private_host 192.168.1.2;! private_host 8.8.8.8;echo 'network self-test: OK';return; };[[ -t 0 && -t 1 ]]||{ echo 'TTY required';exit 1; };tput civis 2>/dev/null||:;local rq r;rq=$(ask 'Source file or directory' /);[[ -e $rq || -b $rq ]]||{ ui;echo "Source does not exist: $rq";waitkey;return 2; };SRC=$(real "$rq");SRC_KIND=$(kindof "$SRC");if [[ $SRC_KIND == block ]];then SDEV=$SRC;SFS=$(lsblk -ndo FSTYPE "$SRC" 2>/dev/null|head -1);SFS=${SFS:-unknown};else read -r _ SDEV SFS _ <<<"$(mountinfo "$SRC")";fi;SMEDIA=$(media "$SDEV" "$SFS");SLINK=$(linkmb "$SDEV");explain;source_info;transport_choose;if [[ $TRANSPORT == rsync-ssh ]];then network_config||return $?;remote_fs_probe;DST='/__remote_destination__';log "SRC=$SRC KIND=$SRC_KIND DEV=$SDEV FS=$SFS MEDIA=$SMEDIA LINK=$SLINK";log "DST_REMOTE=$(ssh_target):$REMOTE_PATH FS=$DFS MEDIA=$DMEDIA";if [[ $SRC_KIND == directory || $SRC_KIND == mountpoint ]];then base_ex;mount_selector;else EX=();fi;yes 'Run safe zstd CPU benchmark in tmpfs?' N&&cpu_bench||:;STRAT=rsync;ui;echo 'Direct network mode selected: rsync over SSH.';echo 'The transfer is incremental and does not require a local staging backup.';echo 'Archive/image formats are available through the Local backup → SCP mode instead.';echo;waitkey;format_options;SIDE=();ZIP_PASS=0;GPG_PASS=0;OUT="$(ssh_target):$REMOTE_PATH";OUT_KIND=remote;else choose_dst;[[ -d $DST && $(findmnt -T "$DST" -rn -o TARGET) == "$DST" ]]||{ echo 'Destination must be a mountpoint';exit 2; };read -r _ DDEV DFS _ <<<"$(mountinfo "$DST")";DMEDIA=$(media "$DDEV" "$DFS");DLINK=$(linkmb "$DDEV");log "SRC=$SRC KIND=$SRC_KIND DEV=$SDEV FS=$SFS MEDIA=$SMEDIA LINK=$SLINK";log "DST=$DST DEV=$DDEV FS=$DFS MEDIA=$DMEDIA LINK=$DLINK";if [[ $SRC_KIND == directory || $SRC_KIND == mountpoint ]];then base_ex;mount_selector;else EX=();fi;yes 'Run safe zstd CPU benchmark in tmpfs?' Y&&cpu_bench||:;yes 'Run destination I/O benchmark with temporary file?' N&&io_bench||:;strategy;format_options;home_root;passwords;nameout;if [[ $TRANSPORT == scp-after ]];then network_config||return $?;fi;fi;summary;yes 'Confirmation 1/2: Is this plan correct?' N||return;yes 'Confirmation 2/2: Are you SURE you want to start?' N||return;if execute;then r=0;else r=$?;fi;ui;if ((r==0));then [[ $TRANSPORT == rsync-ssh ]]&&echo "Network backup completed: $(ssh_target):$REMOTE_PATH"||echo "Backup completed. Output: $OUT";else echo "Backup failed rc=$r";fi;echo "Log: $LOG";return "$r"; }
log "START app=$APP ver=$VER uid=$UID bash=$BASH_VERSION"
main "$@"
